### ISSUE TITLE
Compilation problem: cannot find -lboost_*-mt  libraries with standard Boost installations

### ISSUE THREAD

**Issue by anpefi** [heavywatal/tumopp#19]
Hi, 
thanks for making this software available. It is very interesting for me.

I had problems to install tumopp because of the linking to boost libraries.

Here is the error I have (in three different computers with different ways of installing Boost [Ubuntu packages, built from source, using a module):
```
g++ -std=c++14 -O2 -fPIC  -mfpmath=sse -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -I/home/uvi/be/apf/local/include -I/usr/local/include -DNDEBUG -ftemplate-depth=512 -L/home/uvi/be/apf/local/lib -L/home/uvi/be/apf/local/boost-gcc/lib -L/usr/local/lib -m64 -msse -msse2 -msse3 -o libtumopp.so -shared -Wl,-soname,/home/uvi/be/apf/local/lib/libtumopp.so -Wl,-rpath,/home/uvi/be/apf/local/lib -Wl,-rpath,/home/uvi/be/apf/local/boost-gcc/lib build/cell.o build/simulation.o build/tissue.o -lsfmt -lboost_program_options-mt -lboost_filesystem-mt -lboost_system-mt -lboost_iostreams-mt 
/opt/cesga/gcc/6.1.0/bin/ld: cannot find -lboost_program_options-mt
/opt/cesga/gcc/6.1.0/bin/ld: cannot find -lboost_filesystem-mt
/opt/cesga/gcc/6.1.0/bin/ld: cannot find -lboost_system-mt
/opt/cesga/gcc/6.1.0/bin/ld: cannot find -lboost_iostreams-mt
collect2: error: ld returned 1 exit status
make[2]: *** [libtumopp.so] Error 1
make[2]: Leaving directory `/mnt/EMC/Home_FT2/home/uvi/be/apf/soft/tumopp'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/mnt/EMC/Home_FT2/home/uvi/be/apf/soft/tumopp'
make: *** [release] Error 2
```

I could fix it by removing the sufix "-mt" in the list of libraries in the Makefile:34
`LDLIBS := -lsfmt -lboost_program_options -lboost_filesystem -lboost_system -lboost_iostreams #-lboost_zlib
`

I am assuming that those libraries are the same, but I ignore if this could have any hidden effect. Anyway, installation should be standardized.

Cheers

**Comment by heavywatal** [comment]
Thank you for the comment. Yes, I agree. This program needs more standardized installation. Now I am learning how to use CMake and believing it should solve this problem. Please give me a moment.

The reason why I chose `-mt` version (built with `--layout=tagged` option), by the way, was that [Homebrew](https://brew.sh/)/Linuxbrew did so.

**Comment by heavywatal** [comment]
Now tumopp can be installed with CMake on macOS, Linux, and Cygwin. Thanks again.
