### ISSUE TITLE
[suggestion] Add carrying capacity and time to end to approximate logistic growth

### ISSUE THREAD

**Issue by anpefi** [heavywatal/tumopp#20]
Hi,

for my simulations I'm interested in cases where the run doesn't stop when reaching the limit N, but that it continues evolving with that carrying capacity during a defined time t (close to logistic growth). So, the population grows as it does now until reach N, and then during a time t (if t=0 is the same case as it is now) births only could happen if there are deaths to not pass the N carrying capacity.

I've already forked the repo and I will try to make the modifications myself (although it would take long as I need to understand all the code before) and then make a pull request. But I think it would be faster if you could add this feature as it would be quite trivial for you and I think it would be an useful enhancement for general use of tumopp.

Cheers,
Andrés.

**Comment by heavywatal** [comment]
Thank you for the suggestion. I agree. It will be a reasonable extension. The problem is how we implement it.

- Switch to death-birth model (like Moran model?) after reaching a threshold N.
- Introduce carrying capacity, and let the birth rate of each cell be a function of tumor size (as a deterioration of global environment?)

The former seems easier, and the latter seems more natural in a ecological sense.

**Comment by anpefi** [comment]
We have argued on those models too. 

- The switch to Moran-like model when reached a N=K, although it could be unrealistic, it is useful in several aspects when you are interested in differences between the fast growing phase and the "stable" one. It was already used in Williams et al. (BioRxiv https://doi.org/10.1101/096305). In fact this is the way I started to try to implement (little progress yet) as it would be easier. 

- A more realistic model where the birth rate of each cell (and this is also a simplification as the death rate could be also affected) is dependent to population size ([K-N]/K) would emulate closer a logistic growth. But I'm not sure if this yield a significant improvement/difference to the Moran model, although it would add a third growth phase intermediate between the exponential and the stable that could be interesting. However I think this would need an additional parameter to delay the start of the decay phase (i.e. birth rate is not affected until N=K-D) because cancer is expected to have a large exponential growth (but not infinite).

So, I would start with the simplest Moran-like.

**Comment by heavywatal** [comment]
I have just uploaded a quickie commit that added a Moran-like plateau phase after reaching N=K, by simply setting death rate of each cell to the same value as its birth rate. It will work in "Constant-rate" model. More tweaking may be needed to do the right thing in other neighbor-dependent models.
